services:
  mysql:
    image: mysql:8.0
    container_name: zhul-erp-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - zhul_erp_mysql_data:/var/lib/mysql
      - ./sql/build/sql/schema_v1.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./sql/build/data/data_v1.sql:/docker-entrypoint-initdb.d/02-data.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: zhul-erp-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  zhul_erp_mysql_data:
